config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, sign_out_via: [:get, :post]
  resources  :foods,:users,:public_recipes,:shopping_list
  resources :recipes do
    resources :recipe_foods, only: [:new, :create, :destroy]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'recipes#index'
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.where(public: true)
  end

  def destroy
    @recipe = Recipe.where(public: true).find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
    end
  end
end

app/views/public_recipes/index.html.erb
<h4 class="fw-bold">Public Recipes</h4>
<div class="form-container">
  <ul class="m-0 p-0">
    <% @recipes.each do |recipe| %>
    <li class="card list-style-none mb-3">
      <div class="card-header fs-4">
        <%= link_to recipe.name, recipe_path(recipe.id), style:"text-decoration: none;" %>
      </div>
      <div class="card-body">
        <p class="card-title fw-bold">By: <%= recipe.user.name %></p>
        <p class="card-text fs-6 mb-4">
          <span class="fw-bold">Description:</span><br />
          <%= recipe.description %>
        </p>
        <div class="d-flex justify-content-between">
          <span class="card-text fw-bold"
            >Total food items: <%= recipe.recipe_foods.length || 0 %> </span
          ><br />
          
          <%= button_to 'Remove',
             public_recipe_path(recipe), method: :delete,
             class: "btn", style: "border: 1px solid #e7720b; width: 109px; border-radius: 8px; padding: 10px 20px; text-decoration: none; color: #000; margin-left: 9px; display: inline-block; text-align: center;",
             data: { confirm: 'Are you sure you want to delete this recipe?' } %>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
</div>