config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, sign_out_via: [:get, :post]
  resources  :foods,:users,:public_recipes,:shopping_list
  resources :recipes do
    resources :recipe_foods, only: [:new, :create, :destroy]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'recipes#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
 
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, :preparation_time, :description, presence: true

  def total_cost
    total = 0
    recipe_foods.includes(:food).each do |recipe_food|
      total += recipe_food.quantity * recipe_food.food.price
    end
    total.round(2)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # before_action :set_recipe, only: %i[show edit update destroy]
  before_action :authenticate_user!
  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = RecipeFood.where(recipe_id: @recipe.id)
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_path, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    # @recipe = find_recipe

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def public
    @recipes = Recipe.where(public: true)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
  <div class="form">
      <div class="">
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :preparation_time %>
    <%= form.time_field :preparation_time, style: "border: 1px solid #e7720b; padding: 5px; border-radius: 4px; width: 99%;" %>
  </div>

  <div class="field">
    <%= form.label :cooking_time %>
    <%= form.time_field :cooking_time, style: "border: 1px solid #e7720b; padding: 5px; border-radius: 4px; width: 99%;" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, style: "border: 1px solid #e7720b; padding: 5px; border-radius: 4px; width: 99%;" %>
  </div>

  <div class="field">
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div class="field">
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit "Add Recipe", class: "btn btn-success" %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>
  <div class="itime">
  <p>
    <strong>Preparation time:</strong>
    <%= recipe.preparation_time %>
  </p>

  <p>
    <strong>Cooking time:</strong>
    <%= recipe.cooking_time %>
  </p>
  </div>
 <div class="descri">
  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= recipe.public %>
  </p>
  </div>

  <div  class="username">
  <p>
  <strong>User:</strong>
  <%= recipe.user_id %>
  </p>

  <p>
  <%= recipe.user.name %>
  </p>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render partial: 'form', locals: { recipe: @recipe } %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="recipe">
<h1>Recipes</h1>

<div id="recipes",class="d-flex flex-column align-items-center gap-3  recipei",  style="border-width:0.5rem;">
  <% @recipes.each do |recipe| %>
    <div class="recipei">
    <%= render recipe %>
    <div class="actions">
      <%= link_to "Show this recipe", recipe , style: "border: 1px solid #e7720b; width: 190px; border-radius: 8px; padding: 10px 20px; text-decoration: none; color: #000; margin-left: 9px; display: inline-block; text-align: center;"%>
    </div>
    </div>
  <% end %>
</div>

<%= link_to "New recipe", new_recipe_path, style: "border: 1px solid #e7720b; width: 190px; border-radius: 8px; padding: 10px 20px; text-decoration: none; color: #000; margin-left: 9px; display: inline-block; text-align: center;" %>
</div>

app/views/recipes/new.html.erb
<div  class=form-container>
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>
 
<br>

<div class="link-containers">
  <%= link_to "Back to recipes", recipes_path , style: "border: 1px solid #e7720b; padding: 10px; border-radius: 7px; color: #000; text-decoration: none; " %>
</div>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="recipei">
<%= render @recipe %>
</div>

<div class="links-show">
  <%= link_to "Edit this recipe", edit_recipe_path(@recipe), style: "border: 1px solid #e7720b; width: 190px; border-radius: 8px; padding: 10px 20px; text-decoration: none; color: #000; margin-left: 9px; display: inline-block; text-align: center;" %>
  <%= link_to "Back to recipes", recipes_path, style: "border: 1px solid #e7720b; width: 190px; border-radius: 8px; padding: 10px 20px; text-decoration: none; color: #000; margin-left: 9px; display: inline-block; text-align: center;"%>

  <%= button_to "Destroy this recipe", @recipe, method: :delete, style: "border: 1px solid #e7720b; width: 190px; border-radius: 8px; padding: 10px 20px; text-decoration: none; color: #000; margin-left: 9px; display: inline-block; text-align: center;"%>
  <%= link_to "Generate", shopping_list_index_path, style: "border: 1px solid #e7720b; width: 190px; border-radius: 8px; padding: 10px 20px; text-decoration: none; color: #000; margin-left: 9px; display: inline-block; text-align: center;"%>
  <%= link_to "Add Ingredients", new_recipe_recipe_food_path(@recipe), style: "border: 1px solid #e7720b; width: 190px; border-radius: 8px; padding: 10px 20px; text-decoration: none; color: #000; margin-left: 9px; display: inline-block; text-align: center;" %>
</div>

<%# generate should navigate to shopping_list index page
add ingredients should navigate to recipe_food_new
recipe_food create action in the recipe food controller should redirect to recipe view show page %>