config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, sign_out_via: [:get, :post]
  resources  :foods,:users,:public_recipes,:shopping_list
  resources :recipes do
    resources :recipe_foods, only: [:new, :create, :destroy]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'recipes#index'
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  has_many :recipe_foods, foreign_key: :food_id

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, numericality: { greater_than: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    # @foods = Food.all
    @foods = current_user.foods
    @cuser = current_user
  end

  def show
    @foods = Food.all
  end

  def new
    @foods = Food.all 
    @food = Food.new
  end

  def create
    @food = Food.all
    # @food = Food.new(food_params)
    @food = current_user.foods.new(food_params)

    if @food.save
      redirect_to foods_path
    else
      render :new, status: 'Error occured with Food!'
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path
  end

  private

  def food_params
    params.require(:foods).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/views/foods/_food.html.erb
<div class="border border-5">
<div>
<% @foods.each do |food|  %>
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Measurement unit:</strong>
    <%= food.measurement_unit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= food.quantity %>
  </p>

  <p>
    <strong>User:</strong>
    <%= food.user_id %>
  </p>
<%end%>
</div>

app/views/foods/_form.html.erb
<%= form_with model: @food, class: "form", scope: :foods do |f| %>

    <div class="mb-3">
    <%= f.label :Name, class: "form-label" %>
    <%= f.text_field :name, placeholder: "Add Name of Food", required: true, class: "form-control" %>
    </div>

    <div class="mb-3">
    <%= f.label :Measurement_Unit, class: "form-label" %>
    <%= f.text_field :measurement_unit, placeholder: "Enter Measurement Unit", required: true, class: "form-control" %>
    </div>
    
    <div class="mb-3">
    <%= f.label :Unit_Price, class: "form-label" %>
    <%= f.text_field :price, placeholder: "Unit Price", required: true, class: "form-control" %>
    </div>

    <div class="mb-3">
    <%= f.label :Quantity, class: "form-label" %>
    <%= f.text_field :quantity, placeholder: "Quantity", required: true, class: "form-control" %>
    </div>

    <%= f.submit "Add Food", class: "btn btn-primary" %>
  <% end %>
</div>
  

app/views/foods/index.html.erb
<div class="my-3 float-right" style="background-color: #e7720b; width: 150px; border-radius: 8px; padding-left: 29px">
  <%= link_to "Add Food", new_food_path, class: "btn", style: "margin-left: 2px;" %>
</div>

<div class="my-2">
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Food</th>
        <th>Measurement Unit</th>
        <th>Unit Price</th>
        <th>Quantity</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each_with_index do |food, index| %>
        <tr>
          <td><%= index+1 %></td>
          <td><%= food.name %></td>
          <td><%= food.measurement_unit %></td>
          <td><%= food.price %></td>
          <td><%= food.quantity %></td>
          <td>
            <%= button_to "Delete", food_path(food.id), method: :delete, class: "btn", style: "border: 1px solid #e7720b; width: 150px; border-radius: 8px; padding-left: 29px margin-left: 2px;" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<div class="form-container">
  <h3 class="h3">Add New Food</h3>
  <%= form_with model: @food, class: "form", scope: :foods do |f| %>

    <div class="field">
      <%= f.label :name, "Food", class: "form-label" %>
      <%= f.text_field :name, placeholder: "Food", required: true, class: "form-input" %>
    </div>

    <div class="field">
      <%= f.label :measurement_unit, class: "form-label" %>
      <%= f.text_field :measurement_unit, placeholder: "Enter Measurement Unit", required: true, class: "form-input" %>
    </div>
    
    <div class="field">
      <%= f.label :price, class: "form-label" %>
      <%= f.text_field :price, placeholder: "Unit Price", required: true, class: "form-input" %>
    </div>

    <div class="field">
      <%= f.label :quantity, class: "form-label" %>
      <%= f.number_field :quantity, placeholder: "Quantity", required: true, style: "border: 1px solid #e7720b; padding: 5px; border-radius: 4px; width: 99%;"%>
    </div>
    
    <div class="actions">
      <%= f.submit "Add Food", class: "btn btn-success" %>
    </div>
  <% end %>
</div>