config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, sign_out_via: [:get, :post]
  resources  :foods,:users,:public_recipes,:shopping_list
  resources :recipes do
    resources :recipe_foods, only: [:new, :create, :destroy]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'recipes#index'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar">
<div class="bar-e">
<h1  class="navbar-brand" style="color:#fff;  font-size: 4.5rem">Recipes</h1> 
<%= image_tag 'logo.png', alt: 'recipe', class: "imgbar" %>
    </div>
    <div class="bardiv" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0  ulbar">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Foods', foods_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Recipes', recipes_path, class: "nav-link"%>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'Public Recipes', public_recipes_path, class: "nav-link"%> 
        </li>
        
      </ul>
      <ul class="logoutu">
        <% if user_signed_in? %>
          <li class="nav-item">
          <li class="nav-item">Logged in as <strong><%= current_user.email %></strong>
          <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link'%></li>
          <% else %>
          <%= link_to "Sign up", new_registration_path(resource_name), class: 'navbar-link' %>    |
              <%= link_to "Sign in", new_user_session_path, class: 'navbar-link' %></li>
          <% end %>
        </ul>
      </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  <%= render 'layouts/navbar' %>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>